import {
  BookOpen,
  FileSearch,
  Search,
  Code,
  Braces,
  TrendingUp,
  Gauge,
  MapPin,
  Target,
  Calculator,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export interface Tool {
  slug: string
  title: string
  headline: string
  description: string
  longDescription: string
  icon: LucideIcon
  color: string
  gradient: string
  category: string
  featured?: boolean
  features: { title: string; description: string }[]
  metaTitle: string
  metaDescription: string
  metaKeywords: string[]
}

export const TOOLS: Tool[] = [
  {
    slug: 'sxo-playbook-2026',
    title: 'The SXO Playbook for 2026',
    headline: 'The Complete Search Experience Optimization Playbook',
    description: 'The definitive guide to Search Experience Optimization. 60+ pages of strategies, frameworks, and actionable tactics for dominating search in 2026.',
    longDescription: 'Search Experience Optimization (SXO) is the evolution of SEO. It combines technical SEO, UX design, conversion optimization, and content strategy into a unified framework. This playbook gives you everything you need to implement SXO across your entire digital presence and outrank your competition in 2026.',
    icon: BookOpen,
    color: 'text-orange-500',
    gradient: 'from-orange-500 to-red-500',
    category: 'Strategy',
    featured: true,
    features: [
      { title: 'SXO Framework', description: 'Complete methodology for combining SEO + UX + CRO into one strategy' },
      { title: 'Core Web Vitals Mastery', description: 'Step-by-step guide to achieving perfect performance scores' },
      { title: 'Content Architecture', description: 'How to structure content for maximum search visibility and engagement' },
      { title: 'Conversion Optimization', description: 'Turn organic traffic into leads with SXO-driven landing pages' },
      { title: 'AI-Powered Search', description: 'Prepare your content for AI Overviews, SGE, and zero-click search' },
      { title: 'E-E-A-T Signals', description: 'Build Experience, Expertise, Authority, and Trust signals that Google rewards' },
      { title: 'Technical SXO Audit', description: 'Complete checklist for crawlability, indexability, and structured data' },
      { title: 'Measurement & KPIs', description: 'Track the metrics that actually matter for search experience' },
    ],
    metaTitle: 'The SXO Playbook for 2026 | Free Download | RocketClients',
    metaDescription: 'Download the complete Search Experience Optimization playbook. 60+ pages of SXO strategies, frameworks, and tactics to dominate search in 2026. Free guide.',
    metaKeywords: ['SXO', 'search experience optimization', 'SEO 2026', 'SXO playbook', 'search optimization guide'],
  },
  {
    slug: 'content-audit',
    title: 'Content Audit Tool',
    headline: 'AI-Powered Content Analysis',
    description: 'Analyze any page for content quality, SEO optimization, readability, and conversion potential with our AI-powered audit.',
    longDescription: 'Our Content Audit Tool uses advanced AI to analyze your web pages across 8 critical dimensions. Get actionable insights on content quality, keyword optimization, readability scores, and conversion potential — all in one comprehensive report delivered to your inbox.',
    icon: FileSearch,
    color: 'text-cyan-500',
    gradient: 'from-cyan-500 to-blue-500',
    category: 'Analysis',
    features: [
      { title: 'Title & Meta Analysis', description: 'Evaluate title tags, meta descriptions, and header hierarchy' },
      { title: 'Content Quality Score', description: 'AI-powered assessment of depth, uniqueness, and value' },
      { title: 'Media & Images', description: 'Check alt tags, file sizes, lazy loading, and visual content ratio' },
      { title: 'Link Analysis', description: 'Internal/external link audit with broken link detection' },
      { title: 'Keyword Optimization', description: 'Keyword density, placement, and semantic relevance scoring' },
      { title: 'Readability Score', description: 'Flesch-Kincaid grade level and reading ease metrics' },
      { title: 'Performance Check', description: 'Page load impact of content, scripts, and media' },
      { title: 'Conversion Signals', description: 'CTA placement, form optimization, and user flow analysis' },
    ],
    metaTitle: 'Free Content Audit Tool | AI-Powered Page Analysis | RocketClients',
    metaDescription: 'Analyze any web page for content quality, SEO optimization, readability, and conversion potential. Free AI-powered content audit tool from RocketClients.',
    metaKeywords: ['content audit', 'content analysis tool', 'SEO content checker', 'page analyzer', 'content quality'],
  },
  {
    slug: 'seo-analyzer',
    title: 'SEO Site Analyzer',
    headline: 'Complete Technical SEO Analysis',
    description: 'Run a full technical SEO audit on any website. Check crawlability, indexability, Core Web Vitals, and 50+ ranking factors.',
    longDescription: 'Our SEO Site Analyzer performs a comprehensive technical audit of your website, checking over 50 ranking factors across crawlability, indexability, site speed, mobile-friendliness, and more. Get a prioritized action plan to improve your search rankings.',
    icon: Search,
    color: 'text-green-500',
    gradient: 'from-green-500 to-emerald-500',
    category: 'Analysis',
    features: [
      { title: 'Crawlability Check', description: 'Robots.txt, sitemaps, and crawl budget analysis' },
      { title: 'Indexability Audit', description: 'Canonical tags, noindex directives, and pagination review' },
      { title: 'Core Web Vitals', description: 'LCP, FID, CLS, and INP performance metrics' },
      { title: 'Mobile Responsiveness', description: 'Mobile-first indexing readiness and viewport testing' },
      { title: 'HTTPS & Security', description: 'SSL certificate, mixed content, and security headers check' },
      { title: 'Structured Data', description: 'Schema markup validation and rich snippet eligibility' },
      { title: 'Page Speed Analysis', description: 'Server response time, render-blocking resources, and caching' },
      { title: 'Competitor Benchmarks', description: 'Compare your technical SEO against top competitors' },
    ],
    metaTitle: 'Free SEO Site Analyzer | Technical SEO Audit Tool | RocketClients',
    metaDescription: 'Run a complete technical SEO audit on any website. Check 50+ ranking factors including Core Web Vitals, crawlability, and structured data. Free SEO analyzer.',
    metaKeywords: ['SEO analyzer', 'site audit', 'technical SEO', 'SEO checker', 'website analysis'],
  },
  {
    slug: 'meta-tag-generator',
    title: 'Meta Tag Generator',
    headline: 'Generate Perfect Meta Tags Instantly',
    description: 'Create optimized title tags, meta descriptions, Open Graph tags, and Twitter Cards that drive clicks and improve rankings.',
    longDescription: 'Stop guessing at your meta tags. Our Meta Tag Generator creates perfectly optimized title tags, meta descriptions, Open Graph properties, and Twitter Card markup based on proven SEO best practices and character limits. Copy-paste ready HTML code.',
    icon: Code,
    color: 'text-violet-500',
    gradient: 'from-violet-500 to-purple-500',
    category: 'Generator',
    features: [
      { title: 'Title Tag Optimization', description: 'Generate titles within the 50-60 character sweet spot' },
      { title: 'Meta Description', description: 'Compelling descriptions that maximize CTR in search results' },
      { title: 'Open Graph Tags', description: 'Perfect Facebook and LinkedIn preview tags with image specs' },
      { title: 'Twitter Card Markup', description: 'Summary and large image card markup for Twitter/X' },
      { title: 'Canonical URL', description: 'Proper canonical tag generation for duplicate content prevention' },
      { title: 'Robots Meta', description: 'Index/noindex and follow/nofollow directive generation' },
      { title: 'Character Counter', description: 'Real-time character counts against Google display limits' },
      { title: 'HTML Export', description: 'Copy-paste ready HTML code for your page head section' },
    ],
    metaTitle: 'Free Meta Tag Generator | SEO Title & Description Tool | RocketClients',
    metaDescription: 'Generate optimized meta tags, Open Graph tags, and Twitter Cards instantly. Free meta tag generator with character counting and HTML export.',
    metaKeywords: ['meta tag generator', 'SEO tags', 'title tag generator', 'meta description', 'Open Graph'],
  },
  {
    slug: 'schema-markup-generator',
    title: 'Schema Markup Generator',
    headline: 'Create Rich Snippet Structured Data',
    description: 'Generate JSON-LD schema markup for local business, products, articles, FAQs, and more. Get rich snippets in Google.',
    longDescription: 'Schema markup helps search engines understand your content and display rich snippets in search results. Our generator creates valid JSON-LD structured data for the most impactful schema types, helping you stand out in search results with stars, prices, FAQs, and more.',
    icon: Braces,
    color: 'text-amber-500',
    gradient: 'from-amber-500 to-orange-500',
    category: 'Generator',
    features: [
      { title: 'Local Business', description: 'NAP data, hours, reviews, and geo-coordinates schema' },
      { title: 'Product Schema', description: 'Price, availability, reviews, and offer markup' },
      { title: 'Article Schema', description: 'News, blog post, and how-to article structured data' },
      { title: 'FAQ Schema', description: 'Expandable FAQ rich snippets for SERP real estate' },
      { title: 'Organization', description: 'Company info, logo, social profiles, and contact points' },
      { title: 'Breadcrumbs', description: 'Navigation breadcrumb markup for site hierarchy' },
      { title: 'Validation', description: 'Built-in validation against Google rich result requirements' },
      { title: 'JSON-LD Export', description: 'Copy-paste ready JSON-LD code for your website' },
    ],
    metaTitle: 'Free Schema Markup Generator | JSON-LD Structured Data | RocketClients',
    metaDescription: 'Generate valid JSON-LD schema markup for local business, products, articles, FAQs, and more. Get rich snippets in Google search results. Free tool.',
    metaKeywords: ['schema markup generator', 'JSON-LD', 'structured data', 'rich snippets', 'schema.org'],
  },
  {
    slug: 'keyword-research',
    title: 'Keyword Research Tool',
    headline: 'Discover High-Impact Keywords',
    description: 'Find profitable keywords with search volume, difficulty scores, and intent analysis. Uncover content gaps your competitors miss.',
    longDescription: 'Our Keyword Research Tool helps you discover untapped keyword opportunities by analyzing search volume, keyword difficulty, user intent, and competitive landscape. Find the exact terms your target audience is searching for and build a content strategy that drives qualified traffic.',
    icon: TrendingUp,
    color: 'text-pink-500',
    gradient: 'from-pink-500 to-rose-500',
    category: 'Research',
    features: [
      { title: 'Search Volume Data', description: 'Monthly search volume estimates with trend indicators' },
      { title: 'Difficulty Scoring', description: 'Keyword difficulty ratings based on SERP competition' },
      { title: 'Intent Classification', description: 'Informational, commercial, transactional, and navigational intent' },
      { title: 'Related Keywords', description: 'LSI and semantically related keyword suggestions' },
      { title: 'Question Keywords', description: 'People Also Ask and question-based keyword opportunities' },
      { title: 'Long-Tail Discovery', description: 'Low-competition long-tail keyword variations' },
      { title: 'SERP Analysis', description: 'Current top-ranking pages and content format insights' },
      { title: 'Content Gap Report', description: 'Keywords your competitors rank for that you don\'t' },
    ],
    metaTitle: 'Free Keyword Research Tool | Find Profitable Keywords | RocketClients',
    metaDescription: 'Discover high-impact keywords with search volume, difficulty scores, and intent analysis. Find content gaps and keyword opportunities. Free keyword research tool.',
    metaKeywords: ['keyword research', 'keyword tool', 'keyword finder', 'SEO keywords', 'keyword analysis'],
  },
  {
    slug: 'page-speed-analyzer',
    title: 'Page Speed Analyzer',
    headline: 'Optimize Your Site Performance',
    description: 'Measure page load times, Core Web Vitals, and get actionable recommendations to make your website lightning fast.',
    longDescription: 'Site speed directly impacts your search rankings, user experience, and conversion rates. Our Page Speed Analyzer measures your Core Web Vitals, identifies performance bottlenecks, and provides prioritized recommendations for faster load times across mobile and desktop.',
    icon: Gauge,
    color: 'text-emerald-500',
    gradient: 'from-emerald-500 to-teal-500',
    category: 'Analysis',
    features: [
      { title: 'Core Web Vitals', description: 'LCP, FID/INP, and CLS measurements with pass/fail indicators' },
      { title: 'Mobile Performance', description: 'Mobile-specific speed test on 4G network simulation' },
      { title: 'Resource Analysis', description: 'JavaScript, CSS, and image size breakdown' },
      { title: 'Render Blocking', description: 'Identify render-blocking resources slowing first paint' },
      { title: 'Image Optimization', description: 'Uncompressed images and modern format opportunities' },
      { title: 'Caching Analysis', description: 'Browser cache and CDN configuration review' },
      { title: 'Server Response', description: 'TTFB and server-side performance metrics' },
      { title: 'Priority Actions', description: 'Ranked list of fixes by estimated performance impact' },
    ],
    metaTitle: 'Free Page Speed Analyzer | Core Web Vitals Test | RocketClients',
    metaDescription: 'Measure page speed, Core Web Vitals, and get actionable performance recommendations. Optimize load times for better rankings. Free speed test tool.',
    metaKeywords: ['page speed', 'site speed test', 'Core Web Vitals', 'page performance', 'speed analyzer'],
  },
  {
    slug: 'local-seo-checker',
    title: 'Local SEO Checker',
    headline: 'Dominate Local Search Results',
    description: 'Audit your local SEO presence across Google Business Profile, citations, reviews, and local ranking factors.',
    longDescription: 'Local search is how customers find businesses near them. Our Local SEO Checker audits your Google Business Profile, local citations, review presence, and on-page local SEO signals to help you appear in the Local Pack and Maps results for your target service areas.',
    icon: MapPin,
    color: 'text-blue-500',
    gradient: 'from-blue-500 to-indigo-500',
    category: 'Analysis',
    features: [
      { title: 'GBP Audit', description: 'Google Business Profile completeness and optimization score' },
      { title: 'Citation Check', description: 'NAP consistency across major business directories' },
      { title: 'Review Analysis', description: 'Review volume, rating average, and response rate metrics' },
      { title: 'Local Keywords', description: 'Location-based keyword targeting and optimization' },
      { title: 'Map Pack Tracking', description: 'Current Local Pack ranking positions for target keywords' },
      { title: 'Schema Validation', description: 'LocalBusiness schema markup verification' },
      { title: 'Competitor Comparison', description: 'Side-by-side local SEO benchmarking' },
      { title: 'Action Plan', description: 'Prioritized steps to improve local search visibility' },
    ],
    metaTitle: 'Free Local SEO Checker | GBP Audit & Local Rankings | RocketClients',
    metaDescription: 'Audit your local SEO presence including Google Business Profile, citations, reviews, and local ranking factors. Free local SEO checker tool.',
    metaKeywords: ['local SEO', 'local SEO checker', 'Google Business Profile', 'local search', 'local rankings'],
  },
  {
    slug: 'competitor-analysis',
    title: 'Competitor Analysis Tool',
    headline: 'Outperform Your Competition',
    description: 'Analyze competitor websites to uncover their SEO strategy, top-performing content, backlink sources, and keyword gaps.',
    longDescription: 'Understanding your competition is the fastest path to outranking them. Our Competitor Analysis Tool reveals their top-performing pages, keyword rankings, content strategy, and backlink profile — giving you a strategic roadmap to capture their market share.',
    icon: Target,
    color: 'text-red-500',
    gradient: 'from-red-500 to-rose-500',
    category: 'Research',
    features: [
      { title: 'Top Pages Analysis', description: 'Discover competitor pages driving the most organic traffic' },
      { title: 'Keyword Gap Report', description: 'Keywords they rank for that you\'re missing' },
      { title: 'Content Strategy', description: 'Content types, publishing frequency, and topic clusters' },
      { title: 'Backlink Profile', description: 'Top referring domains and link building opportunities' },
      { title: 'Technical Comparison', description: 'Side-by-side technical SEO and speed benchmarks' },
      { title: 'SERP Overlap', description: 'Shared keywords and head-to-head ranking positions' },
      { title: 'Social Presence', description: 'Social media engagement and content distribution analysis' },
      { title: 'Opportunity Score', description: 'Ranked opportunities by difficulty and potential impact' },
    ],
    metaTitle: 'Free Competitor Analysis Tool | SEO Competitive Research | RocketClients',
    metaDescription: 'Analyze competitor websites to uncover SEO strategy, top content, backlinks, and keyword gaps. Free competitor analysis tool from RocketClients.',
    metaKeywords: ['competitor analysis', 'competitive research', 'SEO competitor', 'competitor keywords', 'gap analysis'],
  },
  {
    slug: 'cro-calculator',
    title: 'CRO Calculator',
    headline: 'Calculate Your Conversion ROI',
    description: 'Estimate the revenue impact of improving your conversion rate. See how small CRO changes can transform your bottom line.',
    longDescription: 'Conversion Rate Optimization has the highest ROI of any marketing activity. Our CRO Calculator shows you exactly how much revenue you\'re leaving on the table and the projected impact of improving your conversion rate by even a fraction of a percent. Make the business case for CRO with real numbers.',
    icon: Calculator,
    color: 'text-teal-500',
    gradient: 'from-teal-500 to-cyan-500',
    category: 'Calculator',
    features: [
      { title: 'Revenue Projection', description: 'See potential revenue at different conversion rates' },
      { title: 'Traffic Impact', description: 'Calculate the value of each additional visitor' },
      { title: 'A/B Test Planning', description: 'Required sample size and test duration estimates' },
      { title: 'Funnel Analysis', description: 'Stage-by-stage drop-off and improvement opportunities' },
      { title: 'Cost Per Lead', description: 'True CPL at different conversion rates' },
      { title: 'LTV Projection', description: 'Customer lifetime value impact of better conversion' },
      { title: 'Break-Even Analysis', description: 'When CRO investment pays for itself' },
      { title: 'Benchmark Data', description: 'Industry-specific conversion rate benchmarks' },
    ],
    metaTitle: 'Free CRO Calculator | Conversion Rate ROI Estimator | RocketClients',
    metaDescription: 'Calculate the revenue impact of improving your conversion rate. Free CRO calculator with traffic, revenue, and ROI projections for your business.',
    metaKeywords: ['CRO calculator', 'conversion rate', 'CRO ROI', 'conversion optimization', 'revenue calculator'],
  },
]

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug)
}

export function getRelatedTools(currentSlug: string, count = 3): Tool[] {
  const current = getToolBySlug(currentSlug)
  if (!current) return TOOLS.slice(0, count)
  const sameCategory = TOOLS.filter((t) => t.slug !== currentSlug && t.category === current.category)
  const others = TOOLS.filter((t) => t.slug !== currentSlug && t.category !== current.category)
  return [...sameCategory, ...others].slice(0, count)
}
